worker_processes 1;
events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    access_log off;
    error_log /dev/null warn;

    server {
        listen 8000;
        server_name _;

        location /ws {
            proxy_pass http://127.0.0.1:10000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header Sec-WebSocket-Extensions "";
            proxy_read_timeout 60s;
            proxy_send_timeout 10s;
        }

        location /xhttp-one {
            proxy_pass http://127.0.0.1:10001;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_read_timeout 60s;
            proxy_send_timeout 10s;
        }

        location /xhttp-up {
            proxy_pass http://127.0.0.1:10002;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_read_timeout 60s;
            proxy_send_timeout 10s;
        }
    }
}
